### ISSUE TITLE
Filtrowanie z wykorzystaniem char_length

### ISSUE THREAD

**Issue by ad-m** [scibi/django-teryt#3]
Wydaje mi się, że wykorzystanie char_length(id) to nie jest najlepsze rozwiązanie. 
```
# TERC
class WojewodztwoManager(models.Manager):
    def get_queryset(self):
        return super(WojewodztwoManager,
                     self).get_queryset().extra(where=["char_length(id) = 2"])


class PowiatManager(models.Manager):
    def get_queryset(self):
        return super(PowiatManager,
                     self).get_queryset().extra(where=["char_length(id) = 4"])


class GminaManager(models.Manager):
    def get_queryset(self):
        return super(GminaManager,
                     self).get_queryset().extra(where=["char_length(id) = 7"])
```
Generalnie extra to nie jest coś zalecanego, bo może rodzić problemy z kompatybilnością z różnymi bazami danych. 

Ja natomiast spotkałem wadę tego rozwiązania, bowiem nie można także na poziomie modelu skonfigurować, aby np. wyłącznie gminy można było wybrać za pomocą  ForeignKey.limit_choices_to. Wyklucza to w praktyce użycie tego pakietu w moim oprogramowaniu.

Proponuje dodać nowe pole, zmodyfikować metodę save, aby filtrować po dodatkowym polu i przygotować migracje.

**Comment by scibi** [comment]
Masz na myśli dodatnie pola z informacją o typie jednostki podziału administracyjnego (województwo/powiat/gmina)?
Jeżeli tak to pytanie czy łączyć to z rodzajem gminy, który zgodnie ze specyfikacja ma takie wartości:
```
1 - gmina miejska,
2 - gmina wiejska,
3 - gmina miejsko-wiejska,
4 - miasto w gminie miejsko-wiejskiej,
5 - obszar wiejski w gminie miejsko-wiejskiej,
8 - dzielnica w m.st. Warszawa,
9 - delegatura gminy miejskiej
```
A może po prostu dodać pole nazwa dodatkowa (`NAZDOD` w `TERC`)?

**Comment by scibi** [comment]
Ajajaj. Na szybko spojrzałem w kod i to nie tego modelu co trzeba... Proponuję aby w modelu `JednostkaAdministracyjna` zamiast metody `typ` zrobić pole o takiej nazwie i wyliczać jego wartość przy zapisywaniu. @ad-m pasuje?

**Comment by ad-m** [comment]
O czym takim jak dodatkowe pole właśnie myślałem. Jednak zaimplementowałem w swoim projekcie już https://bitbucket.org/ad_m/django-teryt, więc z nim pozostanę. Miałem nadzieje, że będę mógł przenieść się na coś zarządzanego zewnątrz.

U mnie model wykorzystuje django-mptt. Ma to swoje plusy (poniżej), a także minusy np. powolne ładowanie danych. Dane są ładowane raz, więc nie traktuje tego za coś istotnego.

Widzę już kolejne use case, które nie będzie mieć przyjemnej obsługi z Twoją paczką. Dla mnie TERYT służy do przedstawiania jakiś danych w ujęciu geograficznym (model z polem FK). U Ciebie nie mogę wyświetlić w prosty sposób wszystkich danych z województwa. W prosty sposób, czyli bez budowania jakiegoś nieprzekonywującego mnie warunku zależnego od poziomu i jeżdżącego po bazie w stylu Q(parent="A") | Q(parent__parent="A") | Q(parent__parent="A"). Przy zastosowaniu mojej paczki mam z django-mptt na modelu metodę get_descendants ( http://django-mptt.github.io/django-mptt/models.html#get-descendants-include-self-false ). i mogę sobie zrobić:
```python
def register_teryt(request, slug):
    context = {}

    object = get_object_or_404(Teryt, slug=slug)
    context['object'] = object

    object_list = Register.objects.filter(teryt__in=object.get_descendants(True)).all()
    context['object_list'] = object_list

    return render(request, 'registers/register_list_teryt.html', context)
```

U mnie kod importu wypadałoby, abym poprawił, ale działa.

**Comment by ad-m** [comment]
W https://github.com/ad-m/django-teryt/commit/d9f51e4744b43e6bf01398c575afbe0cf7e7c459 dodałem django-mptt. Brakuje migracji dla wypełnienia pola danymi, gdy już jakieś są.

Bez MPTT wyświetlenie regionu byłoby jednak możliwe z użyciem `.filter(startswith=obj.id).`, lecz dalej `limit_choices_to` wymagałoby dodatkowego pola, które tutaj samo się dodało i wypełnia przy okazji rebuild().

**Comment by scibi** [comment]
Hmmm. Ja tworząc ten kod potrzebowałem po prostu mieć dostęp do danych z systemu TERYT. Najważniejszy był import ponieważ chciałem potem móc sobie porobić jakieś SQLowe zapytania na poszczególnych zbiorach danych. Jako najbardziej uniwersalne przyjąłem zaimportowanie danych "jak są". Myślę, że pole typ dodam. Natomiast co do robienia drzewa i używania django-mptt to jeszcze pomyślę. Ty skupiłeś się tylko na TERC. A może trzeba zastanowić się czy nie połączyć w drzewo TERC, SIMC i ULIC?
