### ISSUE TITLE
Wydanie PyPI

### ISSUE THREAD

**Issue by ad-m** [scibi/django-teryt#9]
Hej,

Planujesz nowe wydanie PyPI? Usprawniono obsługę MySQL i nowych wersji Django. Myślę, że uzasadnia to wydanie nowej wersji

Z wyrazami szacunku,

**Comment by scibi** [comment]
Cześć!

Tak, planuję :) Chciałem jeszcze dorzucić obsługę typów jednostek. Niestety
ostatnio mam sporo zadań o wyższym priorytecie. Mam nadzieje, że w tym
tygodniu uda się temat ogarnąć i wypuścić nową wersję wspierającą również
sqlite'a.
Co do poprawek w dokumentacji PR są zawsze mile widziane ;)

Hej,

Planujesz nowe wydanie PyPI? Usprawniono obsługę MySQL i nowych wersji
Django. Myślę, że uzasadnia to wydanie nowej wersji

Z wyrazami szacunku,

—
Reply to this email directly or view it on GitHub
<https://github.com/scibi/django-teryt/issues/9>.

**Comment by ad-m** [comment]
Co do dokumentacji - mój język angielski nie pozwala na merytoryczne zmiany. Ale już naprawiłem ;-)
